name: Meg Project Unitests

on:
   push:
   pull_request:

jobs:
   test:
      runs-on: "ubuntu-latest"
      steps:
         - name: Checkout
           uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2         
         - name: Install Dependencies
           run: |
               sudo apt-get update
               sudo apt-get install -y cmake ninja-build wget libxxhash-dev
               wget https://apt.llvm.org/llvm.sh
               chmod +x llvm.sh
               sudo ./llvm.sh 22 || exit 1
         
         - name: Configure
           run: |
               export CC=clang-22
               export CXX=clang++-22
               cmake -B build -G Ninja --preset=Unitests -DCMAKE_C_COMPILER=clang-22 -DCMAKE_CXX_COMPILER=clang++-22
         
         - name: Build
           run: cmake --build build
           
         - name: Run
           run: ctest --test-dir build --output-on-failure
